server:
  port: 8081
application:
  api-clients:
    customers:
      base-url: ${CUSTOMERS_API_PROVIDER_URL:http://localhost:8080/api/v1}
      # connection-timeout: 100
      # response-timeout: 1000