server:
  port: 8080
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
application:
  customers:
    initialization:
      enabled: ${CUSTOMERS_INITIALIZATION_ENABLED:false}
logging:
  level:
    org:
      springframework:
        test:
          context:
            cache: DEBUG